<?php $this->headScript()->offsetSetFile(1009, PUBLIC_FOLDER . '/js/formadepago.js'); ?>

<div class="sabios-row left-column">
    <div class="inline2 sabios-label sabios-row"><h1>Formas de Pago:</h1></div>
    <div class="sabios-row separador"></div>
    <div class="sabios-row sabios-label">AGREGAR NUEVA FORMA DE PAGO</div>
    <div class="sabios-row">
        <form id="fdp-form" action="/formadepago/add" method="POST">
            <div class="inline">
                <input class="sabios-input fdp" type="text" placeholder="Ingrese Nombre para la Nueva Forma de Pago" id="nombre" value="" name="nombre">
            </div>
            <div class="inline">
                <input type="submit" class="sabios-submit submit-filter" name="submit" value="Agregar">
            </div>
            
            
        </form>
    </div>
    <div class="sabios-row separador"></div>
    <div class="sabios-row"></div>
    <div class="sabios-row label"><label>Listado de Formas de Pago:</label></div>
    <div class="sabios-row"></div>
</div>
<div class="left-column sabios-table-container sabios-row">
    <div class="sabios-table">

        <div class="sabios-table-head sabios-back-gradient">
            <div class="sabios-table-tr">

                <div class="sabios-table-td" style="width: 50%">Forma de Pago</div>
                <div class="sabios-table-td" style="width: 9%">Porcentaje</div>
                <div class="sabios-table-td sabios-quest" style="width: 24%">(?)</div>
                <div class="sabios-table-td" style="width: 8%">Editar</div>
                <div class="sabios-table-td" style="width: 8%">Borrar</div>
            </div>

        </div>
        <div class="sabios-table-tbody">
            <?php
            $count = 0;
            foreach ($this->fdps as $fdp) :
                ?>
                <div id="tr-data-<?= $fdp->id ?>" class="sabios-table-tr <?= ($count % 2) ? "grey" : ""; ?>">
                    <div class="sabios-table-td" style="width: 50%"><a href=""><?= $fdp->descripcion ?></a></div>
                    <div class="sabios-table-td" style="width: 34%"><a href=""><div class="decimal"><?= $fdp->interes ?></div></a></div>
                    <div class="sabios-table-td" style="width: 8%"><a href="#"><span class="sabios-edit" value="<?= $fdp->id ?>"></span></a></div>
                    <div class="sabios-table-td" style="width: 8%"><a><span value="<?= $fdp->id ?>" class="sabios-delete"></span></a></div>
                </div>
                <div id="tr-form-<?= $fdp->id ?>" class="hide sabios-table-tr <?= ($count % 2) ? "grey" : ""; ?>">
                    <form method="post" id="form-fdp-<?= $fdp->id ?>" action="/formadepago/edit">
                        <div class="sabios-table-td" style="width: 50%"><input class="fdp-" name ="id" type="hidden" value="<?= $fdp->id ?>"></div>
                        <div class="sabios-table-td" style="width: 50%"><input class="fdp-nombre sabios-input fdp" type="text" id="nombre" value="<?= $fdp->descripcion ?>" name="nombre"></div>
                        <div class="sabios-table-td" style="width: 34%"><input class="fdp-porcentaje sabios-input fdp" type="text" id="porcentaje" value="<?= $fdp->interes ?>" name="porcentaje"></div>
                        <div class="sabios-table-td" style="width: 8%"><a href="#"><i class="fdp-grabar fa fa-floppy-o" title="Grabar" value="<?= $fdp->id ?>"></i></a><i title="Cancelar" class="fdp-cancelar fa fa-times" value="<?= $fdp->id ?>"></i></div>
                        <div class="sabios-table-td" style="width: 8%"><a href="#"><span class="sabios-delete"></span></a></div>
                    </form>
                </div>
                <?php
                $count++;
            endforeach;
            ?>                                
        </div>
        <div class="sabios-table-tfooter">
        </div>	
    </div>
</div>
