<?php
$this->headScript()->offsetSetFile(500, PUBLIC_FOLDER . '/js/resetpassword.js');
$this->headLink()->offsetSetStylesheet(657, PUBLIC_FOLDER . '/css/estilos_home.css');
?>
<div class="sabios-container">
    <div class="logo">
        <div class="sabios-row">
            <a href="/home">
                <div class="logo-image">
                    <img alt="Sabios - Gestión de negocios on-line" title="Sabios - Gestión de negocios on-line" src="/images/sabbios-logo.png"/>
                </div>
            </a>    
            <div class="home"></div>
        </div>    
    </div>
    <div class="middle">
        <div class="left-column">
            <form method="post" action="/usuario/resetpassword" id="reset_password_form">
                <input type="hidden" name="email" value="<?= $this->email ?>"/>
                <input type="hidden" name="hash" value="<?= $this->hash ?>"/>
                <h1>
                    Reestablecimiento de Contrase&ntilde;a:
                </h1>
                <div class="sabios-row">
                    Contrase&ntilde;a <br>
                </div>                
                <div class="sabios-row"><input class="sabios-input" placeholder="Contraseña" type="password" name="password" id="password"/>
                </div>
                <div class="password-div">
                    <div class="sabios-row">
                        <div class="fortaleza muy-debil"></div>
                    </div>
                    <div class="sabios-row strenght">Fortaleza: <span>Muy D&eacute;bil</span></div>
                    <div id="desc-container">
                        <div class="sabios-row fort-desc desc-debil">
                            Tu contrase&ntilde;a es f&aacute;cil de adivinar. Prueba de hacer tu contrase&ntilde;a mas larga.
                            <br> Combina letras may&uacute;usculas y min&uacute;sculas. Agrega caracteres especiales.
                            <br>No uses nombres o palabras del diccionario.
                        </div>
                        <div class="sabios-row fort-desc desc-muy-debil">
                            Tu contrase&ntilde;a es f&aacute;cil de adivinar. Prueba de hacer tu contrase&ntilde;a mas larga.
                            <br> Combina letras may&uacute;usculas y min&uacute;sculas. Agrega caracteres especiales.
                            <br>No uses nombres o palabras del diccionario.
                        </div>                
                        <div class="sabios-row fort-desc desc-fuerte">Tu contrase&ntilde;a resistir&aacute; los m&aacute;s sofisticados ataques.
                            Por favor<br> aseg&uacute;rese de recordarla.
                        </div>
                        <div class="sabios-row fort-desc desc-buena">Tu contrase&ntilde;a resistir&aacute; la mayoria de los ataques.
                            Por favor<br>aseg&uacute;rese de recordarla.
                        </div>
                        <div class="sabios-row fort-desc desc-media">Tu contrase&ntilde;a es suficientemente buena para seguir pero es 
                            <br>recomendable que la fortalezca aun m&aacute;s. 
                        </div> 
                    </div>
                </div>
                <div class="sabios-row re-pass"><input class="sabios-input" placeholder="Confirmar tu contraseña" type="password" name="repitePassword" id="repitePassword"/>
                </div>
                <div class="sabios-row">
                    <a href="#">
                        <button class="login-submit">
                            Enviar
                        </button>
                    </a>
                </div>
            </form>
        </div>
        <div class="right-column">
            <div style="float: left; height: 100px;"></div>
            <div class="errors">
                <div class="sabios-row pass-row">
                    <div class="error-field password-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Contrase&ntilde;a Inv&aacute;lida<br></span><span class="white">Por favor prueba ingresa una contrase&ntilde;a</span></div></div>
                </div>
                <div class="sabios-row repite-pass-row">
                    <div class="error-field repitePassword-error pass-coincidencia"><div class="error-arrow"></div><div class="sabios-error"><span class="red">La Contrase&ntilde;a no coincide<br></span><span class="white">Por favor prueba de nuevo</span></div></div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="links">
            <ul>
                <a href="/home/contact"><li>Contacto</li></a>
                <a href="/home/condiciones"><li>Condiciones</li></a>
                <li>Privacidad</li>
                <a href="/home/invest"><li>Inversionistas</li></a>
            </ul>
        </div>
        <div class="social"><a href="https://www.facebook.com/sabiosweb"><img src="/images/fb.png"/></a><a href="https://twitter.com/sabiosweb"><img src="/images/tw.png"/></a></div>
    </div>    
</div>