<?php

echo $this->doctype();

?>
<html>
	<head>
	
	<?php
	echo $this->headTitle();?>
	
	<?php
	echo $this->headMeta()?>
	
	<?php
	echo $this->headScript()?>
	
	<?php
	echo $this->headLink()?>
	
	<?php
	echo $this->headStyle()?>
	
	<?php  
	if (count($this->messages)) {
		echo "
			<script>
			$(document).ready(function(){
		    	mensajeModal('Mensaje','".$this->messages[0]."', 'error');
			});
			</script>
	";
	}
	?>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> 
	
	</head>
	<body class="_showgrid">
	<center>
	<div class="wrapper">
			<div id="header" class="header"><div class="header-image"><img src="<?php echo PUBLIC_FOLDER ?>/images/logo_mul.png" height="100px"></div><div class="fb-login"><a href="/login/facebook/publish_stream"><img src="/images/facebook.png"></a></div></div>
			<?= $this->menu(array(
					array( 'text' => 'Libros', 'href' => '/admin/libro/list', 'selected' => $this->className == 'libro' ? true : false),
					array( 'text' => 'Usuarios', 'href' => '/admin/usuario/list', 'selected' => $this->className == 'usuario' ? true : false ),
					array( 'text' => 'Art&iacute;culos', 'href' => '/admin/articulo/list', 'selected' => $this->className == 'articulo' ? true : false ),
					array( 'text' => 'Comentarios', 'href' => '/admin/comentario/list', 'selected' => $this->className == 'comentario' ? true : false ),
					array( 'text' => 'Sitemap', 'href' => '/sitemap/generate', 'selected' => false ),
					
					)
				); ?>
			<?= $this->botonera(array("actions" => $this->actions, "object" => $this->className)) ?>
			<div align="center" class="main rounded-main" id="main">                
					<?php 
	                	echo $this->layout()->content;
	                	
	                ?>
	        </div>
	        <div id="footer" class="footer">Copyright &#0169; 2011 MejorUnLibro.com</div>
        </div>
     </center>
     <div id="dialog" title="Basic dialog"><div id="innerDialog"></div></div>
     <div id="dialog-confirm" title="Seguro de Borrar?" style="display:none">
		<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Este Item ser&aacute; borrado desea continuar?</p>
	</div>
     <div id="dialog-confirm-public" title="Seguro de Publicar?" style="display:none">
		<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Este Item ser&aacute; publicado desea continuar?</p>
	</div>	
	</body>
</html>
