<?php $this->headScript()->offsetSetFile(1009, PUBLIC_FOLDER . '/js/index.js'); ?>

<div class="sabios-table-container" style="margin-top:0px">
	<div class="sabios-table">

		<div class="sabios-table-head sabios-back-gradient">
			<div class="sabios-table-tr">

				<div class="sabios-table-td" style="width: 50%">Nombre</div>
				<div class="sabios-table-td" style="width: 15%">Fecha</div>
				<div class="sabios-table-td" style="width: 15%">Pais</div>
				<div class="sabios-table-td" style="width: 20%">Provincia</div>
			</div>

		</div>
		<div class="sabios-table-tbody">
			<div class="sabios-table-tr">
				<div class="sabios-table-td"></div>
				<div class="sabios-table-td">No hay clientes nuevos</div>
			</div>    
		</div>
		<div class="sabios-table-tfooter">
			<div class="sabios-table-tr">
			</div>    
		</div>	
	</div>
</div>

<div class="sabios-table-container">
	<div class="sabios-table">

		<div class="sabios-table-head sabios-back-gradient">
			<div class="sabios-table-tr">

				<div class="sabios-table-td" style="width: 15%">Fecha</div>
				<div class="sabios-table-td" style="width: 15%">Nro Pedido</div>
				<div class="sabios-table-td" style="width: 25%">Cliente</div>
				<div class="sabios-table-td" style="width: 15%">Importe</div>
				<div class="sabios-table-td" style="width: 15%">Pais</div>
				<div class="sabios-table-td" style="width: 15%">Provincia</div>
			</div>

		</div>
		<div class="sabios-table-tbody">
			<div class="sabios-table-tr">
				<div class="sabios-table-td"></div>
				<div class="sabios-table-td">No hay pedidos nuevos</div>
			</div>    
		</div>
		<div class="sabios-table-tfooter">
			<div class="sabios-table-tr">
			</div>    
		</div>	
	</div>
</div>




