<?php
//
$this->headScript()->offsetSetFile(500, PUBLIC_FOLDER . '/js/categoria-add.js');
?>
<script>
    $(document).ready(function() {
        $(".sabios-row.tb-close").click(function() {
            $.unblockUI();
        });
    });
</script>
<div class="sabios-container">

    <div class="middle">
        <div class="left-column" style="width: 100%">
            <form method="post" action="" id="categoria-form">
                <h1>Editar Categoria</h1>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <input type="hidden" id="id" name="id" value="<?= $this->categoria->id ?>">                

                <div class="sabios-row label"><label>Nombre</label></div>

                <div class="sabios-row"><input class="sabios-input" placeholder="Nombre de la categoria" type="text" name="nombre" id="nombre" value="<?= $this->categoria->nombre ?>"/>
                    <div class="error-field nombre-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Nombre Inv&aacute;lido<br></span><span class="white">Por favor ingrese su Nombre</span></div></div>
                </div>
                <div class="sabios-row label"><label>Categoria Padre</label></div>

                <div class="categoria">
                    <div class="sabios-row"><div class="sabios-select sabios-input" id="cats"><span>Categoria Padre</span><div class="down-arrow sabios-gradient"></div></div>
                        <div class="error-field categoria-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Debe seleccionar una opci&oacute;n v&aacute;lida<br></span><span class="white">Intenta nuevamente</span></div></div>
                        <input class="input-field" type="hidden" text="<?= $this->parentCategoria ?>" name="parent_id" id="parent_id" value="<?= (isset($this->categoria->parent_id) ? $this->categoria->parent_id : "0") ?>"/>
                    </div>                
                    <div class="sabios-row">                
                        <div class="sabios-row select-container">
                            <div class="sabios-input sabios-option first-option" value="0">Categoria Base</div>
                            <?php foreach ($this->categorias as $categoria) : ?>
                                <div class="sabios-input sabios-option first-option" value="<?= $categoria['id'] ?>"><?= $this->escape($categoria['categoria']) ?></div> 
                            <? endforeach; ?>
                        </div>
                    </div>
                </div>
                <div class="sabios-row"><a href="index/register"><button class="sabios-submit">Editar Categoria</button></a></div>
            </form>            
        </div>
    </div>
    <div class="bottom">
    </div>    
</div>
<div class="textbox tb-login" id="textbox">
    <div class="sabios-row tb-close"></div>
    <div class="sabios-row tb-title login">Iniciar sesi&oacute;n</div>
    <div class="sabios-row"><input class="sabios-input" placeholder="Correo electr&oacute;nico" type="text" name="email" id="email"/></div>
    <div class="sabios-row"><input class="sabios-input" placeholder="Contraseña" type="password" name="password" id="password"/></div>
    <input type="hidden" name="tyc" id="tyc" value="0"/>
    <div class="sabios-row"><div id="check-uncheck" class="check unchecked">Recordar mi cuenta</div></div>
    <div class="sabios-row">
        <a href="index/register">
            <button class="login-submit">
                Enviar
            </button>
        </a>
    </div>  
    <div class="sabios-row"><div class="forgot-pass">&#191;Olvidaste tu contraseña&#63;</div></div>
</div>
<div class="textbox message" id="flashmessenger">
    <div class="sabios-row tb-close"></div>
    <div class="sabios-row tb-image"></div>
    <div class="sabios-row tb-title">Mensaje</div>
    <div class="sabios-row tb-text">
        <?php if (count($this->messages)) : ?>
            <ul id="messages">
                <?php foreach ($this->messages as $message) : ?>
                    <li><?php echo $this->escape($message); ?></li>
                <?php endforeach; ?>
            </ul>
            <script>
                $.blockUI({message: $('#flashmessenger'), css: {'width': '326px', 'border': 'none', 'border-radius': '8px'}});
            </script>
        <?php endif; ?>
    </div>
</div>
<div class="textbox invalid" id="flashmessenger-error">
    <div class="sabios-row tb-close"></div>
    <div class="sabios-row tb-image-invalid"></div>
    <div class="sabios-row tb-title-invalid">&#161;Error&#33;</div>
    <div class="sabios-row tb-text-invalid">
        <?php if (count($this->errormessages)) : ?>
            <ul id="messages">
                <?php foreach ($this->errormessages as $message) : ?>
                    <li><?php echo $this->escape($message); ?></li>
                <?php endforeach; ?>
            </ul>
            <script>
                $.blockUI({message: $('#flashmessenger-error'), css: {'width': '326px', 'border': 'none', 'border-radius': '8px'}});
            </script>
        <?php endif; ?>
    </div>
</div>   