<div class="stock-filters sabios-row">
	<div class="sabios-row" style="margin-left: 10px; margin-bottom: 8px; width: 250px">	
		<div class="sabios-row">
			<div class="sabios-row label">
				<label>Nombre</label>
			</div>
		</div>    
		<div class="sabios-filters">
			<form type="post" id="filter-form">
				<div class="inline">
					<input class="sabios-input" type="text" placeholder="Nombre" id="nombre" value="<?= $this->nombre ?>" name="nombre">
				</div>
			</form>
		</div>
	</div>
	<div class="inline" style="float: left; margin-left: 4 px; margin-top: 31px">
		<input type="submit" class="sabios-submit submit-filter" name="submit" value="Filtrar">
	</div>
</div>
<div class="sabios-table-container">
    <div class="sabios-table">

        <div class="sabios-table-head sabios-back-gradient">
            <div class="sabios-table-tr">

                <div class="sabios-table-td" style="width: 84%">Nombre</div>
                <div class="sabios-table-td" style="width: 8%; text-align: center">Editar</div>
				<div class="sabios-table-td" style="width: 8%; float: right; text-align: center">Borrar</div>

            </div>

        </div>
        <div class="sabios-table-tbody">
<?php 
    $count = 0;
    foreach ($this->categorias as $categoria) : ?>
                <div class="sabios-table-tr <?= ($count % 2) ? "grey":""?>">
                    <div class="sabios-table-td" style="width: 81%;padding-left: 4%;"><a href="/categoria/edit/<?= $categoria['id'] ?>"><?= $categoria['categoria'] ?></a></div>
                    <div class="sabios-table-td" style="width: 4%;padding-left: 2%"><a href="/categoria/edit/<?= $categoria['id'] ?>"><span class="sabios-edit"></span></a></div>
					<div class="sabios-table-td" style="width: 4%;padding-left: 2%; margin-left: 2%"><a href="#" onClick="confirmDelete('<?= $categoria['id'] ?>');"><span class="sabios-delete"></span></a></div>
                 </div>    
<?php $count++;endforeach; ?>                                
        </div>
        <div class="sabios-table-tfooter">
  
        </div>	
    </div>
</div>
<?php
echo $this->paginationControl($this->categorias, 'Sliding', '/partials/my_pagination_control_categorias.phtml', array('object' => $this->object, 'nombre'=> $this->nombre));
?> 