<div class="stock-filters sabios-row sabios-table" style="padding-top: 10px; padding-bottom: 5px">
     <div class="sabios-filters" >
        <form type="post" id="filter-form">
			<div class="inline" style="margin-left: 10px; width: 250px">
				<div class="sabios-row label">
					<label>Buscar Palabra:</label>
				</div>
				<div class="sabios-row">
					<input class="sabios-input" type="text" placeholder="Nombre" id="nombre" value="" name="nombre">
				</div>
			</div>

            <div class="inline" style="float: left; margin-top: 26px; margin-left: 6px">
                <input type="submit" class="sabios-submit submit-filter" name="submit" value="Filtrar">
            </div>
        </form>
    </div>
</div>



<div class="sabios-table-container sabios-row">
    <div class="sabios-table">

        <div class="sabios-table-head sabios-back-gradient">
            <div class="sabios-table-tr">

                <div class="sabios-table-td" style="width: 10%">Id</div>
                <div class="sabios-table-td" style="width: 25%">Nombre</div>
                <div class="sabios-table-td" style="width: 25%">Estado</div>
                <div class="sabios-table-td" style="width: 24%">subdominio</div>
                <div class="sabios-table-td" style="width: 8%">Editar</div>
                <div class="sabios-table-td" style="width: 8%">Borrar</div>

            </div>

        </div>
        <div class="sabios-table-tbody">
            <?php
            $count = 0;
            foreach ($this->objects as $app) :
                ?>
                <div class="sabios-table-tr <?= ($count % 2) ? "grey" : ""; ?>">
                    <div class="sabios-table-td" style="width: 10%"><a href=""><?= $app->id ?></a></div>
                    <div class="sabios-table-td" style="width: 25%"><a href=""><?= $app->nombre ?></a></div>
                    <div class="sabios-table-td" style="width: 25%"><a href=""><?= $app->estado ?></a></div>
                    <div class="sabios-table-td" style="width: 24%"><a href=""><?=  $app->subdominio ?></a></div>
                    <div class="sabios-table-td" style="width: 8%"><a href="/superadmin/edit/<?= $app->id ?>"><span class="sabios-edit"></span></a></div>
                    <div class="sabios-table-td" style="width: 8%"><a onclick="confirmDelete('1');" href="#"><span class="sabios-delete"></span></a></div>
				</div>
                <?php
                $count++;
            endforeach;
            ?>                                
        </div>
        <div class="sabios-table-tfooter">
        </div>	
    </div>
</div>

<div class="textbox invalid" id="flashmessenger-error">
    <div class="sabios-row tb-close"></div>
    <div class="sabios-row tb-image-invalid"></div>
    <div class="sabios-row tb-title-invalid">&#161;Error&#33;</div>
    <div class="sabios-row tb-text-invalid">
            <?php if (count($this->errormessages)) : ?>
            <ul id="messages">
                <?php foreach ($this->errormessages as $message) : ?>
                    <li><?php echo $this->escape($message); ?></li>
    <?php endforeach; ?>
            </ul>
            <script>
                    $.blockUI({message: $('#flashmessenger-error'), css: {'width': '326px', 'border': 'none', 'border-radius': '8px'}});
            </script>
<?php endif; ?>
    </div>
</div>