<div class="listar-ventas1">
	<div class="listar-ventas2">
		<font class="titulo-input1"> 
			Buscar Palabra
		</font> 
		<input class="listar-ventas1" type="text" value="" name="Buscar Palabra" placeholder="Buscar Palabra">
	</div>
	
	<div class="listar-vemtas3">
		<font font-family="helveticaneuelight" font-size= 18px color= #2a1b78> Buscar Palabra </font> 
		<div class="sabios-select sabios-input"></div>
    </div>
</div>
<table class="listar-ventas4">
	<tr>
		<td>
		ID
		</td>
		<td>
		Nombre
		</td>
		<td>
		Tipo de Cliente
		</td>
		<td>
		Editar
		</td>
		<td>
		Borrar
		</td>
	</tr>
	<tr>
		<td>
		(el php que muestra el ID)
		</td>
		<td>
		(el php que muestra el Nombre)
		</td>
		<td>
		(el php que muestra el Tipo de Cliente)
		</td>
		<td>
		(el boton con el php que abre una pestaña del explorador para editar)
		</td>
		<td>
		(el boton con el php que borra)
		</td>
	</tr>
</table>
<table>
	<tr>
		<td>
		(aca va el php o javascrip que muestra la pagina actual)
		</td>
		<td>
		(aca van los botones "Anterior" y "Siguiente" con el php o javaescrip correspondiente"
		</td>
	</tr>
</table>
