<?php
$this->headScript()->offsetSetFile(101, PUBLIC_FOLDER . '/js/validation.js');
echo $this->doctype();
$menuId = APPLICATION_ID == 'admin' ? 3 : 1;
?>

<html>
    <head>

        <link rel="shortcut icon" href="<?= PUBLIC_FOLDER ?>/images/favicon.ico">
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headMeta() ?>

        <?php echo $this->headScript() ?>

        <?php echo $this->headLink() ?>

        <?php echo $this->headStyle() ?>


        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> 

    </head>
    <body>
        <table width="960px" cellspacing="0" cellpadding="0" border="0" align="center" class="bordes_header">
            <tbody><tr>
                    <td width="240" align="center"><img vspace="10" src="/images/sabbios-logo.png"></td>
                    <td width="710" align="right" class="">
                        <div class="dashboard">
                            <div class="newline">Bienvenido, <?= $this->user ?></div>
                            <?php if(APPLICATION_ID !== 'admin') :?>
                                <div class="newline">Tipo de Actividad: Sabios Textil y Calzado</div>
                            <?php endif;?>
                            <div class="newline">Versi&oacute;n: 1.0</div>
                            <div class="newline"><div style="float:left;">Hora:</div><div id="tiempo"></div></div>
                            <div class="newline"><a href="">Home</a> | <a href="/usuario/logout">Cerrar Sessión </a></div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <br>
        <table width="960px" cellspacing="0" cellpadding="0" border="0" align="center">
            <tbody><tr>
                    <td width="230px" style="vertical-align: top;">

                        <table width="" cellspacing="0" cellpadding="0" border="0" align="center" class="texto" style="padding-top:0px; padding-bottom:0px;">
                            <tbody><tr>
                                    <td width="210" valign="top">
                                        <div style="float:left;">
                                            <table width="210" cellspacing="0" cellpadding="0" border="0" class="menu">
                                                <tbody><tr>
                                                        <td style="padding-left:5px; padding-right:5px; padding-top:0px; padding-bottom:20px;"> 
                                                            <!--  -->
                                                            <div align="center" class="titulo_menu" style="padding-bottom:8px">Men&uacute; Principal</div>


                                                            <div class="menu2" id="menu-principal" style="display: block;">
                                                                <?php
                                                                echo '<ul>' . My_Function_Function::getMenuHtml(0,0,$menuId) . '</ul>';
                                                                ?>
                                                            </div>
                                                            <br><br><br><br><br><br>
                                                            <!--  -->
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </td>
                                    <td width="20" valign="top">&nbsp;</td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                    <td style="vertical-align:top; padding-top:0px;" ><?php echo $this->layout()->content; ?></td>
                </tr>
            </tbody></table>
        <div align="center" class="footer"> <a target="_blank" href="">2013</a> 
            &copy; Lider Soft</div>
        <div id="sabios-messagebox" class="hide sabios-table-container sabios-row">
            <div class="sabios-table">
                <div class="sabios-table-head sabios-back-gradient">
                    <div class="sabios-table-tr">

                        <div class="sabios-table-td sabios-table-titulo" style="width: 100%"><span>TITULO</span></div>
                    </div>
                </div>
                <div class="sabios-table-tbody">
                    <div id="description" class="sabios-table-ttr">
                        <p></p>
                    </div>
                    <div class="sabios-table-ttr">
                        <button class="sabios-fdp-submit tb-close">Ok</button>
                    </div>                    
                </div>
                <div class="sabios-table-tfooter">
                </div>	
            </div>
        </div>    
        <div id="sabios-confirm" class="hide sabios-table-container sabios-row">
            <div class="sabios-table">
                <div class="sabios-table-head sabios-back-gradient">
                    <div class="sabios-table-tr">

                        <div class="sabios-table-td sabios-table-titulo" style="width: 100%"><span>TITULO</span></div>
                    </div>
                </div>
                <div class="sabios-table-tbody">
                    <div id="description" class="sabios-table-ttr">
                        <p></p>
                    </div>
                    <div class="sabios-table-ttr">
                        <button class="sabios-fdp-submit option-no">No</button>
                        <button class="sabios-fdp-submit option-yes">Si</button>
                    </div>                    
                </div>
                <div class="sabios-table-tfooter">
                </div>	
            </div>
        </div>
       <?php if(count($this->errormessages)) :
            foreach($this->errormessages as $message) :
            ?>
        <script>
          //  $(document).ready(function() {
            sabiosMessageBox("Error", "<?= $message ?>");
          // });
        
        
        </script>
        <?php endforeach; 
        endif; ?>
       <?php if(count($this->messages)) :
            foreach($this->messages as $message) :
            ?>
        <script>
          //  $(document).ready(function() {
            sabiosMessageBox("Éxito", "<?= $message ?>");
          // });
        
        
        </script>
        <?php endforeach; 
        endif; ?>        
    </body>
</html>
