<?php
$this->headLink()->offsetSetStylesheet(100, PUBLIC_FOLDER . '/css/frontpage.css');
$this->headScript()->offsetSetFile(101, PUBLIC_FOLDER . '/js/validation.js');
echo $this->doctype();
?>

<html>
<head>
<link rel="shortcut icon" href="<?=PUBLIC_FOLDER?>/images/favicon.ico">
	<?php
echo $this->headTitle();
?>
	
	<?php
echo $this->headMeta()?>
	
	<?php
echo $this->headScript()?>
	
	<?php
echo $this->headLink()?>
	
	<?php
echo $this->headStyle()?>


    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

</head>
<body>

	<center>
	
	
		<div class="main" id="main">                
									<?php die("llega!");
		    echo $this->layout()->content;
		    ?>
		</div>
	
	</center>
</body>
</html>