<?php
echo $this->doctype();
?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<?php echo $this->headTitle ()?>

<?php echo $this->headMeta ()?>

<?php echo $this->headScript ()?>

<?php echo $this->headLink ()?>

<?php echo $this->headStyle ()?>

</head>
<body class="_showgrid">
<div class="container">

<?php 
echo $this->layout()->content;
?>
</div>
</body>
</html>