<?php

/**
 * Application
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Application extends BaseApplication
{
    public static function isNameAvailable($name) {

        $art = Doctrine_Query::create()
                ->from("Application a")
                ->where("a.nombre = ?", $name);
        $result = $art->execute()->toArray();
        if (isset($result[0])) {
            return false;
        } else {
            return true;
        }
    }    

}