<?php

/**
 * ArticuloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticuloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticuloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Articulo');
    }
}