<?php

/**
 * AuditoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuditoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuditoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Auditoria');
    }
}