<?php

/**
 * CargoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CargoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CargoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cargo');
    }
}