<?php

/**
 * CategoriaTreeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaTreeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaTreeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoriaTree');
    }
}