<?php

/**
 * ClienteTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClienteTipo');
    }
}