<?php

/**
 * DetallePedidoXTalleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetallePedidoXTalleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetallePedidoXTalleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetallePedidoXTalle');
    }
}