<?php

/**
 * FormaDePagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormaDePagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormaDePagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FormaDePago');
    }
}