<?php

/**
 * NovedadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NovedadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NovedadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Novedad');
    }
}