<?php

/**
 * PagoTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PagoTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PagoTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PagoTipo');
    }
}