<?php

/**
 * PedidoDetalleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PedidoDetalleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PedidoDetalleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PedidoDetalle');
    }
}