<?php

/**
 * PedidoDetallePorTalleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PedidoDetallePorTalleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PedidoDetallePorTalleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PedidoDetallePorTalle');
    }
}