<?php

/**
 * PedidoEstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PedidoEstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PedidoEstadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PedidoEstado');
    }
}