<?php

/**
 * PersonalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Personal');
    }
}