<?php

/**
 * PrivilegioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrivilegioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrivilegioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Privilegio');
    }
}