<?php

/**
 * Producto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Producto extends BaseProducto
{
    
//    public static function isBlocked($id){
//                        $data = Doctrine_Query::create()->select()
//                                ->from('Talle t')
//                                ->where('t.id=' . $id)
//                                ->andWhere("t.app_id='" . APPLICATION_ID . "'")
//                                ->andWhere("t.borrado='N'")->execute();
//                        
//       return $data[0]->bloqueado_usuario_id ? true : false; 
//        
//        
//    }
    
    public function block($userId){
        
        $this->bloqueado_id_usuario = $userId;
        $fecha = new Zend_Date();
        $this->bloqueado_datetime = $fecha->get('yyyy-MM-dd HH:mm:ss');
       // die($this->id);
       try {parent::save();
       }catch(Exception $e) {
           die($e->getMessage());
       }
        
    }
    public function unBlock(){
        
        $this->bloqueado_id_usuario = 0;
        $this->bloqueado_datetime = null;
        $this->save();
        
        
    }
    public function isBlocked($userId){

        return ($this->bloqueado_id_usuario == 0 || is_null($this->bloqueado_id_usuario) || $this->bloqueado_id_usuario == $userId) ? false : true; 
        
        
    }    
            
            

}