<?php

/**
 * ProductoTextilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductoTextilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductoTextilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductoTextil');
    }
}