<?php

/**
 * RecursosPorPerfilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecursosPorPerfilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecursosPorPerfilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RecursosPorPerfil');
    }
}