<?php

/**
 * RecursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Recurso');
    }
}