<?php

/**
 * SiteConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteConfigurationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteConfiguration');
    }
}