<?php

/**
 * SucursalPorClienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SucursalPorClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SucursalPorClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SucursalPorCliente');
    }
}