<?php

/**
 * TallePorProductoTextilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TallePorProductoTextilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TallePorProductoTextilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TallePorProductoTextil');
    }
}