<?php

/**
 * TalleTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TalleTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TalleTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TalleTipo');
    }
}