<?php

/**
 * Usuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usuario extends BaseUsuario {

//    public static function validarUsuario($email, $hash) {
//
//        $user = Doctrine_Core::getTable("Usuario")->findByDql("email='" . $email . "' and validationHash='" . $hash . "' and blockeado='Y'");
//
//        if (is_object($user[0])) {
//            $user[0]->blockeado = 'N';
//            $user[0]->save();
//            return true;
//        } else {
//            return false;
//        }
//    }

    public function save() {
        if (!$this->id) {

            // verificar que no haya un email duplicado
            $art = Doctrine_Query::create()
                    ->from("Usuario U")
                    ->where("U.email = ?", $this->email);
            $result = $art->execute()->toArray();
            if (isset($result[0])) {
                throw new Exception("Email ya registrado por favor ingrese otra dirección");
            }

            // here make the validation hash

            $this->validationHash = md5($this->email . $this->alta);
        }

        try {
            parent::save();
        } catch (Exception $e) {
            die($e->getMessage());
        }
        return true;
    }

    public static function validarUsuario($email, $hash) {

        $art = Doctrine_Query::create()
                ->from("Usuario U")
                ->where("U.email = ?", $email)
                ->andWhere("U.validationHash = ?", $hash)
                ->andWhere("U.blockeado = 'Y'");
        $result = $art->execute()->toArray();
        
        if (isset($result[0])) {
            $user = $art->execute();
            $user[0]->blockeado = 'N';
            $user[0]->save();
            return true;
        }
        else
            return false;
    }

    public static function isAvailableEmail($email) {

        $art = Doctrine_Query::create()
                ->from("Usuario U")
                ->where("U.email = ?", $email);
        $result = $art->execute()->toArray();
        if (isset($result[0])) {
            return false;
        } else {
            return true;
        }
    }
    public static function getUserByEmail($email){
        
        
        $usuario = Doctrine_Query::create()
                        ->from("Usuario u")
                        ->where("u.email = '".$email."'")
                        ->andWhere("u.blockeado='N'")->fetchOne();
        
        return is_object($usuario) ? $usuario : false;
        
    }    

}