<?php

/**
 * VendedorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VendedorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VendedorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vendedor');
    }
}