<?php

/**
 * VentaDetalleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VentaDetalleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VentaDetalleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VentaDetalle');
    }
}