<?php

/**
 * VentaEstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VentaEstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VentaEstadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VentaEstado');
    }
}