<?php

/**
 * VentaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VentaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VentaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Venta');
    }
}