<?php
echo $this->doctype();
?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<?php echo $this->headTitle ()?>

<?php echo $this->headMeta ()?>

<?php echo $this->headScript ()?>

<?php echo $this->headLink ()?>

<?php echo $this->headStyle ()?>

</head>
<body class="_showgrid">
<!-- Start: page-top-outer -->
<div id="page-top-outer"><!-- Start: page-top -->
<div id="page-top"><!-- start logo -->
<div id="logo"></div>
<!-- end logo --> <!--  start top-search -->
<div id="top-search">
<table border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td><input type="text" value="Search"
			onblur="if (this.value=='') { this.value='Search'; }"
			onfocus="if (this.value=='Search') { this.value=''; }"
			class="top-search-inp" /></td>
		<td><select class="styledselect">
			<option value="">Libros</option>
			<option value="">Generos</option>
			<option value="">Articulos</option>
			<option value="">Categorias</option>
			<option value="">Autores</option>
			<option value="">Editoriales</option>
		</select></td>
		<td><input type="image"
			src="/css/newadmin/images/shared/top_search_btn.gif" /></td>
	</tr>
</table>
</div>
<!--  end top-search -->
<div class="clear"></div>

</div>
<!-- End: page-top --></div>
<!-- End: page-top-outer -->

<div class="clear">&nbsp;</div>

<!--  start nav-outer-repeat................................................................................................. START -->
<div class="nav-outer-repeat"><!--  start nav-outer -->
<div class="nav-outer"><!-- start nav-right -->
<div id="nav-right">

<div class="nav-divider">&nbsp;</div>
<div class="showhide-account"><img
	src="/css/newadmin/images/shared/nav/nav_myaccount.gif" width="93"
	height="14" alt="" /></div>
<div class="nav-divider">&nbsp;</div>
<a href="" id="logout"><img
	src="/css/newadmin/images/shared/nav/nav_logout.gif" width="64"
	height="14" alt="" /></a>
<div class="clear">&nbsp;</div>

<!--  start account-content -->
<div class="account-content">
<div class="account-drop-inner"><a href="" id="acc-settings">Settings</a>
<div class="clear">&nbsp;</div>
<div class="acc-line">&nbsp;</div>
<a href="" id="acc-details">Personal details </a>
<div class="clear">&nbsp;</div>
<div class="acc-line">&nbsp;</div>
<a href="" id="acc-project">Project details</a>
<div class="clear">&nbsp;</div>
<div class="acc-line">&nbsp;</div>
<a href="" id="acc-inbox">Inbox</a>
<div class="clear">&nbsp;</div>
<div class="acc-line">&nbsp;</div>
<a href="" id="acc-stats">Statistics</a></div>
</div>
<!--  end account-content --></div>
<!-- end nav-right --> <!--  start nav -->
<div class="nav">
<div class="table">

<ul class="select">
	<li><a href="#nogo"><b>Libros</b><!--[if IE 7]><!--></a><!--<![endif]-->
	<!--[if lte IE 6]><table><tr><td><![endif]-->
		<div class="select_sub">
			<ul class="sub">
				<li><a href="/admin/libro/add">Agregar</a></li>
				<li><a href="/admin/libro/list">Listar</a></li>
			</ul>
		</div>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
</ul>

<div class="nav-divider">&nbsp;</div>

<ul class="select">
	<li><a href="#nogo"><b>Articulos</b><!--[if IE 7]><!--></a><!--<![endif]-->
	<!--[if lte IE 6]><table><tr><td><![endif]-->
		<div class="select_sub">
			<ul class="sub">
				<li><a href="#nogo">Agregar</a></li>
				<li><a href="#nogo">Listar</a></li>
			</ul>
		</div>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
</ul>

<div class="nav-divider">&nbsp;</div>

<ul class="select">
	<li><a href="#nogo"><b>Autores</b><!--[if IE 7]><!--></a><!--<![endif]-->
	<!--[if lte IE 6]><table><tr><td><![endif]-->
		<div class="select_sub">
			<ul class="sub">
				<li><a href="#nogo">Agregar</a></li>
				<li><a href="#nogo">Listar</a></li>
			</ul>
		</div>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
</ul>

<div class="nav-divider">&nbsp;</div>

<ul class="select">
	<li><a href="#nogo"><b>Generos</b><!--[if IE 7]><!--></a><!--<![endif]-->
	<!--[if lte IE 6]><table><tr><td><![endif]-->
		<div class="select_sub">
			<ul class="sub">
				<li><a href="#nogo">Agregar</a></li>
				<li><a href="#nogo">Listar</a></li>
			</ul>
		</div>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
</ul>

<div class="nav-divider">&nbsp;</div>

<ul class="select">
	<li><a href="#nogo"><b>Editoriales</b><!--[if IE 7]><!--></a><!--<![endif]-->
	<!--[if lte IE 6]><table><tr><td><![endif]-->
		<div class="select_sub">
			<ul class="sub">
				<li><a href="#nogo">Agregar</a></li>
				<li><a href="#nogo">Listar</a></li>
			</ul>
		</div>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
</ul>

<div class="nav-divider">&nbsp;</div>

<ul class="select">
	<li><a href="#nogo"><b>Usuarios</b><!--[if IE 7]><!--></a><!--<![endif]-->
	<!--[if lte IE 6]><table><tr><td><![endif]-->
		<div class="select_sub">
			<ul class="sub">
				<li><a href="#nogo">Agregar</a></li>
				<li><a href="#nogo">Listar</a></li>
			</ul>
		</div>
	<!--[if lte IE 6]></td></tr></table></a><![endif]--></li>
</ul>
<div class="nav-divider">&nbsp;</div>
<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
<!--  start nav --></div>
<div class="clear"></div>
<!--  start nav-outer --></div>
<!--  start nav-outer-repeat................................................... END -->

<div class="clear"></div>

<!-- start content-outer ........................................................................................................................START -->
<div id="content-outer"><!-- start content -->
<div id="content">
<div class="bg1">
                <?php 
                echo $this->layout()->content;
                ?>
            </div>
</div>
<!--  end content -->
<div class="clear">&nbsp;</div>
</div>
<!--  end content-outer........................................................END -->

<div class="clear">&nbsp;</div>

<!-- start footer -->
<div id="footer"><!-- <div id="footer-pad">&nbsp;</div> --> <!--  start footer-left -->
<div id="footer-left">All rights reserved.</div>
<!--  end footer-left -->
<div class="clear">&nbsp;</div>
</div>
<!-- end footer -->

</body>
</html>