<div class="sabios-container">  
    <div class="sabios-row">

        <h1>Lo Sentimos Un Error ha ocurrido</h1>
    </div>
    <?php if (isset($this->exception)): ?>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>
            <div class="sabios-row"></div>

        <div class="sabios-row">
            <div class="sabios-exception"><b>Error:</b> <?php echo $this->exception ?>   </div>
        </div>

    </p>
<?php endif ?>
</div>

