<?php
//
//$this->headScript()->offsetSetFile(500, PUBLIC_FOLDER . '/js/producto-add.js');
?>
<script>
    $(document).ready(function () {
        $(".sabios-row.tb-close").click(function () {
            $.unblockUI();
        });
    });
</script>
<div class="sabios-container">

    <div class="middle">
        <div class="left-column" style="width: 100%">
            <form method="post" action="" id="fondo-form">
                <input type="hidden" id="fondo" name="fondo">
                <h1>Cargar Fondo</h1>

                <div class="sabios-row separator"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"><input type="radio" class="" name="tipo" value="0" checked>
                    <label>Seleccionar un fondo predeterminado</label>
                </div>
                <div class="sabios-row"></div>
                <div class="sabios-row">
                    <?php
                    for ($i = 1; $i < 11; $i++):?>
                        <div class="back-example" id="<?= $i ?>">
                            <img src="/images/textures/t<?= $i ?>.png">
                        </div>
                    <?php endfor; ?>
                </div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"><input type="radio" class="" name="tipo" value="1">
                    <label>o Seleccionar una imagen <a class="help" href="javascript:void(0)">(?)</a></label>
                </div>
                <div class="sabios-row">
                    <div id="foto-container" class="foto-container rounded first">
                        <div class="foto-file"><input number="1" id="foto-1" type="file" name="foto-1"></div>
                        <input class="fotoname" type="hidden" name="fotoname-1" id="fotoname-1">
                    </div>
                </div>
                <div class="sabios-row">
                    <button class="sabios-submit">Cargar Fondo</button>
                </div>
            </form>
        </div>
    </div>
    <div class="bottom">
    </div>
</div>
<div class="textbox message" id="flashmessenger">
    <div class="sabios-row tb-close"></div>
    <div class="sabios-row tb-image"></div>
    <div class="sabios-row tb-title">Mensaje</div>
    <div class="sabios-row tb-text">
        <?php if (count($this->messages)) : ?>
            <ul id="messages">
                <?php foreach ($this->messages as $message) : ?>
                    <li><?php echo $this->escape($message); ?></li>
                <?php endforeach; ?>
            </ul>
            <script>
                $.blockUI({
                    message: $('#flashmessenger'),
                    css: {'width': '326px', 'border': 'none', 'border-radius': '8px'}
                });
            </script>
        <?php endif; ?>
    </div>
</div>
<div class="textbox invalid" id="flashmessenger-error">
    <div class="sabios-row tb-close"></div>
    <div class="sabios-row tb-image-invalid"></div>
    <div class="sabios-row tb-title-invalid">&#161;Error&#33;</div>
    <div class="sabios-row tb-text-invalid">
        <?php if (count($this->errormessages)) : ?>
            <ul id="messages">
                <?php foreach ($this->errormessages as $message) : ?>
                    <li><?php echo $this->escape($message); ?></li>
                <?php endforeach; ?>
            </ul>
            <script>
                $.blockUI({
                    message: $('#flashmessenger-error'),
                    css: {'width': '326px', 'border': 'none', 'border-radius': '8px'}
                });
            </script>
        <?php endif; ?>
    </div>
</div>
<script>
    $(document).ready(function () {

        $("#fondo-form").submit(function(){

                if(!$("#fondo").val()){
                    alert("Debe seleccionar un tipo de fondo");
                    return false;
                }
            });


        $(".back-example").click(function () {
            $("body").css("background-image", "url(/images/textures/t" + $(this).attr("id") + ".png)");
            $(".back-example").css("border", "1px dashed");
            $(this).css("border", "1px dashed green");
            $("#fondo").val("/images/textures/t" + $(this).attr("id") + ".png");
        });
        $("input[name=tipo]").change(function () {
            var seleccion = $("input:radio[name=tipo]:checked").val();
            $("body").css("background-image", "none");
        });


        $(".foto-file input").live('change', function () {
            var id = $(this).attr("id");
            $this = $(this);
            $.ajaxFileUpload
            (
                {
                    url: '/browser/ajaxuploadfondo',
                    secureuri: false,
                    fileElementId: id,
                    dataType: 'json',
                    beforeSend: function () {
                        //
                    },
                    complete: function () {
                        //$("#loading").hide();
                    },
                    success: function (data, status) {
                        console.log(data);
                        if (typeof(data.message) !== 'undefined') {
                            if (data.success) {

                                $("body").css("background-image", "url(" + data.publicFolder + "/" + data.fileName +")");
                                $("#fondo").val(data.publicFolder + "/" + data.fileName);
                            } else {
                                alert(data.message);
                            }
                        }
                    },
                    error: function (data, status, e) {
                        alert(e);
                    }
                }
            );
        });
        $(".close").live('click', function () {
            $(this).parent().find("input").val('');
            $(this).parent().find("input").show();
            $(this).parent().find("img").remove();
            $(this).hide();
        });
        $(".help").click(function () {
            sabiosMessageBox("Ayuda", "La imagen puede tener extension jpg gif o png. El tamanio ideal es 400x300");
        });
    });

</script>