<?php
$this->headScript()->offsetSetFile(500, PUBLIC_FOLDER . '/js/forgot.js');
$this->headLink()->offsetSetStylesheet(657, PUBLIC_FOLDER . '/css/estilos_home.css');
?>
<div class="sabios-container">
    <div class="logo">
        <div class="sabios-row">
            <a href="/home">
                <div class="logo-image">
                    <img alt="Sabios - Gestión de negocios on-line" title="Sabios - Gestión de negocios on-line" src="/images/sabbios-logo.png"/>
                </div>
            </a>    
            <div class="home"></div>
        </div>    
    </div>
    <div class="middle">
        <div class="left-column">
            <form method="post" action="/home/forgotpassword" id="forgot_password_form">
                <h1>
                    Recuperaci&oacute;n de Contrase&ntilde;a:
                </h1>
        <div class="sabios-row">
            Complete estos datos para solicitar el cambio de su contrase&ntilde;a.<br>
            Luego recibir&aacute;a un correo con un link para reestablecerla. <br>
        </div>                
                <div class="sabios-row">
                    <input class="sabios-input" placeholder="Ingrese su E-mail" type="text" name="email" id="email" value="<?=$this->email?>"/>
                </div>
                <div class="sabios-row">
                    <a href="#">
                        <button class="login-submit">
                            Enviar
                        </button>
                    </a>
                </div>
            </form>
        </div>
        <div class="right-column">
            <div style="float: left; height: 100px;"></div>
            <div class="errors">
                <div class="sabios-row error-field email-error">
                    <div class="error-arrow">
                    </div>
                    <div class="sabios-error">
                        <span class="red">
                            Direcci&oacute;n de E-mail Inv&aacute;lida
                            <br>
                        </span>
                        <span class="white">
                            Por favor ingrese una direcci&oacute;n de E-mail correcta
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom">
        <div class="links">
            <ul>
                <a href="/home/contact"><li>Contacto</li></a>
                <a href="/home/condiciones"><li>Condiciones</li></a>
                <li>Privacidad</li>
                <a href="/home/invest"><li>Inversionistas</li></a>
            </ul>
        </div>
        <div class="social"><a href="https://www.facebook.com/sabiosweb"><img src="/images/fb.png"/></a><a href="https://twitter.com/sabiosweb"><img src="/images/tw.png"/></a></div>
    </div>    
</div>