<?php
$this->headScript()->offsetSetFile(500, PUBLIC_FOLDER . '/js/registrarse.js');
?>
<script>
    $(document).ready(function() {
        $(".sabios-row.tb-close").click(function() {
            $.unblockUI();
        });
    });
</script>
<div class="sabios-container">
    <div class="logo">
        <div class="sabios-row">
            <a href="/">
                <div class="logo-image">
                    <img alt="Sabios - Gestión de negocios on-line" title="Sabios - Gestión de negocios on-line" src="/images/sabios-logo.png"/>
                </div>
            </a>    
            <div class="home"></div>
        </div>    
    </div>    
    <div class="middle">
        <div class="left-column" style="width: 100%">
            <form method="post" action="/register" id="register-form">
                <h1>Registrarse:</h1>
                <div class="sabios-row"><input class="sabios-input" placeholder="Nombre" type="text" name="nombre" id="nombre" value="<?= $this->nombre ?>"/>
                    <div class="error-field nombre-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Nombre Inv&aacute;lido<br></span><span class="white">Por favor ingrese su Nombre</span></div></div>
                </div>
                <div class="sabios-row"><input class="sabios-input" placeholder="Apellido" type="text" name="apellido" id="apellido" value="<?= $this->apellido ?>"/>
                    <div class="error-field apellido-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Apellido Inv&aacute;lido<br></span><span class="white">Por favor ingrese su Apellido</span></div></div>
                </div>
                <div class="sabios-row"><input class="sabios-input" placeholder="E-mail" type="text" name="email" id="email" value="<?= $this->email ?>"/>
                    <div class="error-field email-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Direcci&oacute;n de E-mail Inv&aacute;lida<br></span><span class="white">Por favor ingrese una direcci&oacute;n de E-mail correcta</span></div></div>
                </div>
                <div class="sabios-row"><input class="sabios-input" placeholder="Contraseña" type="password" name="password" id="password"/>
                    <div class="error-field password-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Contrase&ntilde;a Inv&aacute;lida<br></span><span class="white">Por favor prueba ingresa una contrase&ntilde;a</span></div></div>
                </div>
                <div class="password-div">
                    <div class="sabios-row">
                        <div class="fortaleza muy-debil"></div>
                    </div>
                    <div class="sabios-row strenght">Fortaleza: <span>Muy D&eacute;bil</span></div>
                    <div id="desc-container">
                        <div class="sabios-row fort-desc desc-debil">
                            Tu contrase&ntilde;a es f&aacute;cil de adivinar. Prueba de hacer tu contrase&ntilde;a mas larga.
                            <br> Combina letras may&uacute;usculas y min&uacute;sculas. Agrega caracteres especiales.
                            <br>No uses nombres o palabras del diccionario.
                        </div>
                        <div class="sabios-row fort-desc desc-muy-debil">
                            Tu contrase&ntilde;a es f&aacute;cil de adivinar. Prueba de hacer tu contrase&ntilde;a mas larga.
                            <br> Combina letras may&uacute;usculas y min&uacute;sculas. Agrega caracteres especiales.
                            <br>No uses nombres o palabras del diccionario.
                        </div>                
                        <div class="sabios-row fort-desc desc-fuerte">Tu contrase&ntilde;a resistir&aacute; los m&aacute;s sofisticados ataques.
                            Por favor<br> aseg&uacute;rese de recordarla.
                        </div>
                        <div class="sabios-row fort-desc desc-buena">Tu contrase&ntilde;a resistir&aacute; la mayoria de los ataques.
                            Por favor<br>aseg&uacute;rese de recordarla.
                        </div>
                        <div class="sabios-row fort-desc desc-media">Tu contrase&ntilde;a es suficientemente buena para seguir pero es 
                            <br>recomendable que la fortalezca aun m&aacute;s. 
                        </div> 
                    </div>
                </div>
                <div class="sabios-row re-pass"><input class="sabios-input" placeholder="Confirmar tu contraseña" type="password" name="repitePassword" id="repitePassword"/>
                    <div class="error-field repitePassword-error pass-coincidencia"><div class="error-arrow"></div><div class="sabios-error"><span class="red">La Contrase&ntilde;a no coincide<br></span><span class="white">Por favor prueba de nuevo</span></div></div>
                </div>
                <div class="sabios-row"><input class="sabios-input" placeholder="NOMBREDECUENTA" type="text" name="cuenta" id="cuenta" value="<?= $this->cuenta ?>"/>
                    <div class="error-field cuenta-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Debe ingresar un nombre v&aacute;lido.<br></span><span class="white">Solo letras, numeros por favor</span></div></div>
                </div>
                <div class="sabios-row"><div class="sabios-select sabios-input" id="tipodecuenta"><span>Tipo de Actividad</span><div class="down-arrow sabios-gradient"></div></div>
                    <div class="error-field tipodecuenta-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Debe seleccionar una opci&oacute;n v&aacute;lida<br></span><span class="white">Intenta nuevamente</span></div></div>
                    <input type="hidden" name="tipoactividad" id="tipoactividad" value="<?= (isset($this->tipoactividad) ? $this->tipoactividad : "0") ?>"/>
                </div>
                <div class="sabios-row">                
                    <div class="sabios-row select-container">
                        <div class="sabios-input sabios-option first-option" value="0">Tipo de Actividad</div> 
                        <div class="sabios-input sabios-option first-option" value="Sabios Textil y Calzado">Sabios Textil y Calzado</div> 
                        <div class="sabios-input sabios-separator">Proximamente:</div> 
                        <div class="sabios-input no-elegible" value="0">Sabios Kiosko</div> 
                        <div class="sabios-input no-elegible last-option" value="0">Sabios Bar y Restaurant</div>          
                    </div>
                </div>
                <div class="sabios-row"><input class="sabios-input" placeholder="web de su empresa" type="text" name="web" id="web" value="<?= $this->web ?>"/>
                    <div class="error-field web-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Debe ingresar una direcci&oacute;n v&aacute;lida<br></span><span class="white">Intenta nuevamente</span></div></div>
                </div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"></div>
                <div class="sabios-row"><h1>Datos del Responsable</h1></div>
                <div class="sabios-row"><input class="sabios-input" placeholder="Nombre y Apellido" type="text" name="responsablenombre" id="responsablenombre" value="<?= $this->responsablenombre ?>"/></div>
                <div class="sabios-row"><input class="sabios-input" placeholder="Email" type="text" name="responsableemail" id="responsableemail" value="<?= $this->responsableemail ?>"/>
                    <div class="error-field responsableemail-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">Direcci&oacute;n de E-mail Inv&aacute;lida<br></span><span class="white">Por favor ingrese una direcci&oacute;n de E-mail correcta</span></div></div>

                </div>
                <div class="sabios-row"><input class="sabios-input" placeholder="Tel&eacute;fono" type="text" name="responsabletelefono" id="responsabletelefono" value="<?= $this->responsabletelefono ?>"/></div>
                <div class="sabios-row"><input class="sabios-input" placeholder="Direcci&oacute;n" type="text" name="responsabledireccion" id="responsabledireccion" value="<?= $this->responsabledireccion ?>"/></div>
                <input type="hidden" name="tyc" id="tyc" value="0"/>
                <div class="sabios-row"><div id="check-uncheck" class="check unchecked">Estoy de acuerdo con las <a href="/index/condiciones">Condiciones</a> y <a href="/index/privacidad">Privacidad</a> de Sabios.</div>
                    <div class="error-field tyc-error"><div class="error-arrow"></div><div class="sabios-error"><span class="red">T&eacute;rminos y Condiciones<br></span><span class="white">Por favor acepte antes de continuar</span></div></div>
                </div>
                <div class="sabios-row"><a href="index/register"><button class="login-submit">Crear Cuenta</button></a></div>
            </form>            
        </div>
    </div>
    <div class="bottom">
        <div class="links">
            <ul>
                <a href="/index/contact"><li>Contacto</li></a>
                <a href="/index/condiciones"><li>Condiciones</li></a>
                <a href="/index/privacidad"><li>Privacidad</li></a>
                <a href="/"><li>home</li></a>
            </ul>
        </div>
        <div class="social"><a href="https://www.facebook.com/sabiosweb"><img src="/images/fb.png"/></a><a href="https://twitter.com/sabiosweb"><img src="/images/tw.png"/></a></div>
    </div>    
</div>
<div class="textbox tb-login" id="textbox">
    <div class="sabios-row tb-close"></div>
    <div class="sabios-row tb-title login">Iniciar sesi&oacute;n</div>
    <div class="sabios-row"><input class="sabios-input" placeholder="Correo electr&oacute;nico" type="text" name="email" id="email"/></div>
    <div class="sabios-row"><input class="sabios-input" placeholder="Contraseña" type="password" name="password" id="password"/></div>
    <input type="hidden" name="tyc" id="tyc" value="0"/>
    <div class="sabios-row"><div id="check-uncheck" class="check unchecked">Recordar mi cuenta</div></div>
    <div class="sabios-row">
        <a href="index/register">
            <button class="login-submit">
                Enviar
            </button>
        </a>
    </div>  
    <div class="sabios-row"><div class="forgot-pass">&#191;Olvidaste tu contraseña&#63;</div></div>
</div>
<div class="textbox message" id="flashmessenger">
    <div class="sabios-row tb-close"></div>
    <div class="sabios-row tb-image"></div>
    <div class="sabios-row tb-title">Mensaje</div>
    <div class="sabios-row tb-text">
        <?php if (count($this->messages)) : ?>
            <ul id="messages">
                <?php foreach ($this->messages as $message) : ?>
                    <li><?php echo $this->escape($message); ?></li>
                <?php endforeach; ?>
            </ul>
            <script>
                $.blockUI({message: $('#flashmessenger'), css: {'width': '326px', 'border': 'none', 'border-radius': '8px'}});
            </script>
        <?php endif; ?>
    </div>
</div>
<div class="textbox invalid" id="flashmessenger-error">
    <div class="sabios-row tb-close"></div>
    <div class="sabios-row tb-image-invalid"></div>
    <div class="sabios-row tb-title-invalid">&#161;Error&#33;</div>
    <div class="sabios-row tb-text-invalid">
        <?php if (count($this->errormessages)) : ?>
            <ul id="messages">
                <?php foreach ($this->errormessages as $message) : ?>
                    <li><?php echo $this->escape($message); ?></li>
                <?php endforeach; ?>
            </ul>
            <script>
                $.blockUI({message: $('#flashmessenger-error'), css: {'width': '326px', 'border': 'none', 'border-radius': '8px'}});
            </script>
        <?php endif; ?>
    </div>
</div>